apiVersion: v1
kind: Pod
metadata:
  name: proxy
  namespace: kube-system
spec:
  hostNetwork: true
  containers:
  - name: proxy
    image: gcr.io/google_containers/hyperkube:v1.1.7
    command: [
      "/hyperkube",
      "proxy",
      "--master={{.APIServerURL}}",
      "--kubeconfig=/var/run/kubelet/kubeconfig",
      "--v=2"
    ]
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /var/run/kubelet/kubeconfig
      name: kubeconfig
      readOnly: true
  volumes:
  - name: kubeconfig
    hostPath:
      path: /var/run/kubelet/kubeconfig
